# Generated by Django 2.0 on 2018-03-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180128_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='sent_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '修改邮箱')], max_length=30, verbose_name='发送类型'),
        ),
    ]
