# Generated by Django 2.0 on 2018-02-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [

    ]
