# Generated by Django 2.0 on 2018-02-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_category'),
    ]

    operations = [

    ]
