# Generated by Django 2.0 on 2018-02-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180225_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='necessary',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(default='', max_length=300, verbose_name='教师提示'),
        ),
    ]
