# Generated by Django 2.0 on 2018-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='organization',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
