# Generated by Django 2.0 on 2018-03-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tag',
            field=models.CharField(default='全国知名', max_length=10, verbose_name='机构标签'),
        ),
    ]
